Batch commit of work from 28 Sep to 1 Dec 2009
This collects about 80 commits from 28 Sep 2009 to 1 Dec 2009 that are
mostly unrelated to the build system and the impending single-scons change.
These commits were missed in the original googlecode export and there
was no time to extract them properly.

[Rewriting history to fix repo structure - LCS]

diff --git a/scons-tools/casacore_assay b/scons-tools/casacore_assay
--- a/scons-tools/casacore_assay
+++ b/scons-tools/casacore_assay
@@ -176,23 +176,19 @@ EOF
      STATUS=0
      exit
   fi
-  # Not fully equal, check if equal except for numbers.
-  # Replace for this purpose all numbers by x.
-  sed -e 's/[+-]\?\(\(\([0-9]\+\)\|\([0-9]*\.\?[0-9]*\)\)\(e[+-]\?[0-9]\+\)\?\)/x/g' ${1}_tmp.out > ${1}_tmp.out2
-  sed -e 's/[+-]\?\(\(\([0-9]\+\)\|\([0-9]*\.\?[0-9]*\)\)\(e[+-]\?[0-9]\+\)\?\)/x/g' ${1}_tmpo.out > ${1}_tmpo.out2
-  diff ${1}_tmp.out2 ${1}_tmpo.out2 > /dev/null 2>&1
-  if [ $? != 0 ]
-  then
-     echo "FAIL (output not verified): $1"
-     STATUS=2
-     exit
-  fi
-  if floatcheck.sh ${1}_tmp.out ${1}_tmpo.out 1e-5
-  then
+  # Not fully equal. Check with floating point accuracy.
+  casacore_floatcheck ${1}_tmp.out ${1}_tmpo.out 1e-5
+  stat=$?
+  case $stat in
+  0)
      echo "PASS (floating point discrepancies <= 1e-5): $1"
-     STATUS=0
-     exit
-  fi
-  echo "FAIL (floating point discrepancies > 1e-5): $1"
-  STATUS=2
+     ;;
+  1)
+     echo "FAIL (output not verified): $*"
+     ;;
+  *)
+     echo "FAIL (floating point discrepancies > 1e-5): $1"
+     ;;
+  esac
+  STATUS=$stat
   exit
