Do the actual commit and make it robust for commit failures

diff --git a/code/install/docutils/ac b/code/install/docutils/ac
--- a/code/install/docutils/ac
+++ b/code/install/docutils/ac
@@ -133,13 +133,29 @@ a_id=`expr $a_idold + 1 | awk '{printf d4 $1}'`
 \rm -f CHANGELOG.LASTID
 echo $a_id > CHANGELOG.LASTID
 sed $a_pwd/changelog.entry-brief -e "s/-_-chid-_-/$a_id/" >> CHANGELOG.LAST
-##cvs commit -m "ac: set to change-id $a_id" CHANGELOG.LASTID CHANGELOG.LAST
+cvs commit -m "ac: set to change-id $a_id" CHANGELOG.LASTID CHANGELOG.LAST
+a_sts=$?
+\rm -f CHANGELOG.LASTID CHANGELOG.LAST
+if [ $a_sts != 0 ]
+then
+  echo "Commit failed; try it later using:  ac -i"
+  exit 1
+fi
 # Update and check in the changelog file.
 cd $a_pwd
 \rm -f changelog
 cvs update changelog
 sed $a_pwd/changelog.entry-full -e "s/-_-chid-_-/$a_id/" >> changelog
-##cvs commit -m "ac: added change-id $a_id" changelog
+cvs commit -m "ac: added change-id $a_id" changelog
+a_sts=$?
+\rm -f changelog
+if [ $a_sts != 0 ]
+then
+  echo "Commit failed; try it later using:  ac -i"
+  exit 1
+fi
+# Commit was successful, so the entry files can be deleted.
+\rm -f changelog.*
 
 
 exit 0
