Changes in usage

diff --git a/code/install/codemgmt/UPchange b/code/install/codemgmt/UPchange
--- a/code/install/codemgmt/UPchange
+++ b/code/install/codemgmt/UPchange
@@ -42,6 +42,7 @@ set usage = 'Usage: UPchange [-c] [-mv] [-t] [-l] [-i] [-mk] [-d] <typ>'
 #   -i  will not check any files in/out, but only work on files in work area
 #   -mk will make the changed files to test if correct
 #   -d  will show some debug information
+#   -n  will only generate the specific data, without executing
 # <typ>.done and <typ>.error give lists of files successfully done or not.
 #
 # See UPinfo for details
@@ -49,14 +50,25 @@ set usage = 'Usage: UPchange [-c] [-mv] [-t] [-l] [-i] [-mk] [-d] <typ>'
 #
 # Get general info
 #
-set x = "`which UPinfo`"
+if (! $?AIPSPATH) then
+   echo "No AIPSPATH environment set, initialize aips++ first"
+   exit 1
+endif
+set x = "`which UPfind`"
 if (-x "$x") then
    set uppath = $x:h
 else
    set x = ( $AIPSPATH )
-   set uppath = $x[1]
+   set uppath = $x[1]/$x[2]/bin
 endif
 unset x
+if ("$uppath" == ".") then
+    set uppath = `pwd`
+endif
+if (! -r $uppath/UPinfo) then
+   echo "Cannot find the UPinfo source script in $uppath"
+   echo "Check your aips++ installation"
+endif
 source $uppath/UPinfo
 if (! $ok) exit 1
 #
@@ -110,7 +122,7 @@ if ($domv) then
       echo "Specify sed patterns to change the names of files to move"
       echo 'Example: s#/Measures#/Quanta#'
       while (1)
-         echo -n 'File pattern: '
+         echo -n 'sed pattern: '
          set x = "$<"
          if ("$x" == "") break
          echo "$x" >> $ldir/${tp}.cfnm
@@ -122,16 +134,20 @@ if ($domv) then
       exit (1)
    endif
    cd $dir/code/
-   foreach i (`cat $ldir/${tp}.sel`)
+   set x = (`cat $ldir/${tp}.sel`)
+   foreach i ($x)
      set j = `echo $i | sed -f $ldir/${tp}.cfnm`
-     if ($upreal) then
+     if ($upreal && ! $nox) then
 	amv -src $i $j
      else
-	echo "amv -src $i $j"
+	echo amv -src $i $j
      endif
    end
    cd $ldir
+   unset x
 endif
+
+if ($nox) exit 0
 
 if ($upaoi) then
    if (! -r $ldir/${tp}.rcs) then
@@ -167,7 +183,7 @@ unset a
 if (-e ${tp}.changed) rm -f ${tp}.changed
 if (! $leav) then
     echo "Change the file names in ${tp}.found (to ${tp}.changed)..."
-    $uppath/UPsed $ldir/$tp ${tp}.found ${tp}.changed force
+    $uppath/UPsed -f $ldir/$tp ${tp}.found ${tp}.changed
 else
     cat ${tp}.found >! ${tp}.changed
 endif
@@ -197,7 +213,7 @@ if (! $upmake) then
 	endif
     endif
     if (-e $i:t) then
-        $uppath/UPsed $ldir/$tp $i:t $i:t force
+        $uppath/UPsed -f $ldir/$tp $i:t $i:t
 	if ($upaoi) $xai $i:t < $ldir/${tp}.rcs
         echo "$i done" >> $ldir/${tp}.done
         if ($xai == rai && $upaoi) rm -f $i:t
@@ -238,7 +254,7 @@ if ($upmake) then
       if ($upaoi) $xao $i:t
       if (-e $i:t) then
           chmod 644 $i:t
-          $uppath/UPsed $ldir/$tp $i:t $i:t force
+          $uppath/UPsed -f $ldir/$tp $i:t $i:t
 	  chmod 444 $i:t
 	  set ok = 0
 	  if (${i:t:e} == cc) then
@@ -271,3 +287,7 @@ if ($upmake) then
 endif
 
 exit 0
+
+
+
+
diff --git a/code/install/codemgmt/UPfind b/code/install/codemgmt/UPfind
--- a/code/install/codemgmt/UPfind
+++ b/code/install/codemgmt/UPfind
@@ -32,7 +32,7 @@ set script = "UPfind"
 set usage = 'Usage: UPfind [-c] [-g] <typ>'
 #
 # UPfind script (must have x allowed)
-# Get all files that have to be updated according to a grep -E rule
+# Get all files that have to be updated according to an egrep rule
 # All .cc, .h and template files are scanned, or the .g if -g given
 # The file list will be in <typ>.raw
 # <typ>.found will have the list without user selected
@@ -42,14 +42,25 @@ set usage = 'Usage: UPfind [-c] [-g] <typ>'
 #
 # Get general info
 #
-set x = "`which UPinfo`"
+if (! $?AIPSPATH) then
+   echo "No AIPSPATH environment set, initialize aips++ first"
+   exit 1
+endif
+set x = "`which UPfind`"
 if (-x "$x") then
    set uppath = $x:h
 else
    set x = ( $AIPSPATH )
-   set uppath = $x[1]
+   set uppath = $x[1]/$x[2]/bin
 endif
 unset x
+if ("$uppath" == ".") then
+    set uppath = `pwd`
+endif
+if (! -r $uppath/UPinfo) then
+   echo "Cannot find the UPinfo source script in $uppath"
+   echo "Check your aips++ installation"
+endif
 source $uppath/UPinfo
 if (! $ok) exit 1
 #
@@ -57,7 +68,7 @@ if (! $ok) exit 1
 #
 if (! -r $ldir/${tp}.up1) then
    touch $ldir/${tp}.up1
-   echo "Specify grep -E expression(s) to find files"
+   echo "Specify egrep  expression(s) to find files"
    echo 'Examples: /Measures/((MUString)|(MVAngle)|(MVTime)|(RotM)|Q|(Un))'
    echo '      or: [(][^(]*[*] *[)][ \t]*0'
    echo 'Multi-line expressions will be ORed'
@@ -71,9 +82,15 @@ if (! -r $ldir/${tp}.up1) then
 endif
 
 if (! -r $ldir/${tp}.rm) then
-   echo "Specify grep pattern for files to be removed from list found."
+   echo "Specify egrep pattern for files to be removed from list found."
    echo "Example: [/]glish[/]"
+   echo "tmplinst files will always be removed"
    echo tmplinst >! $ldir/${tp}.rm
+   echo -n "Remove glish files? (y|n) [y]: "
+   set x = "$<"
+   if ("$x" != "n") then
+      echo '[/]glish[/]' >> $ldir/${tp}.rm
+   endif
    while (1)
 	 echo -n "Remove pattern: "
 	 set x = "$<"
@@ -92,11 +109,11 @@ cd $dir/code
 echo "Starting find..."
 if ($gls) then
    find . -name '*.g' \
-	-exec $upgrep -l -E -f $ldir/${tp}.up1 {} \; \
+	-exec egrep -l -f $ldir/${tp}.up1 {} \; \
 	      >! $ldir/${tp}.raw 
 else
    find . \( \( -name '*.h' -o -name '*.cc' \) -o -name 'templates' \) \
-	-exec $upgrep -l -E -f $ldir/${tp}.up1 {} \; \
+	-exec egrep -l -f $ldir/${tp}.up1 {} \; \
 	      >! $ldir/${tp}.raw 
 endif
 cd $ldir
@@ -106,7 +123,7 @@ echo $a[1] files found in ${tp}.raw
 unset a
 
 echo "Starting selected removal..."
-$upgrep -v -f $ldir/${tp}.rm $ldir/${tp}.raw >! $ldir/${tp}.found
+egrep -v -f $ldir/${tp}.rm $ldir/${tp}.raw >! $ldir/${tp}.found
 
 set a = ( `wc ${tp}.found` )
 echo $a[1] files left in ${tp}.found
diff --git a/code/install/codemgmt/UPsed b/code/install/codemgmt/UPsed
--- a/code/install/codemgmt/UPsed
+++ b/code/install/codemgmt/UPsed
@@ -44,40 +44,64 @@ set usage = 'Usage: UPsed [-f] <typ> <filename in> [<filename out>]'
 #
 # Get general info
 #
-if ($#arg < 1) then
+if ($# < 1) then
     echo "$usage"
     exit (1)
 endif
 
 if ("$1" == "-f") then
     shift
+    set arg = ($*)
 else
-    source UPinfo
-    if (! $ok) exit 1
+   if (! $?AIPSPATH) then
+      echo "No AIPSPATH environment set, initialize aips++ first"
+      exit 1
+   endif
+   set x = "`which UPfind`"
+   if (-x "$x") then
+     set uppath = $x:h
+   else
+     set x = ( $AIPSPATH )
+     set uppath = $x[1]/$x[2]/bin
+   endif
+   unset x
+   if ("$uppath" == ".") then
+     set uppath = `pwd`
+   endif
+   if (! -r $uppath/UPinfo) then
+     echo "Cannot find the UPinfo source script in $uppath"
+     echo "Check your aips++ installation"
+   endif
+   source $uppath/UPinfo
+   if (! $ok) exit 1
 endif
 #
 # Get specific data
 #
-if ($#arg < 1) then
+if ($#arg < 2) then
     echo "$usage"
     exit (1)
 endif
 
-set fin = $1
-if ($#arg < 2) then
+set tp = $arg[1]
+set fin = $arg[2]
+if ($#arg < 3) then
     set fout = $fin
 else
-    set fout = $2
-endif
-
-if (! -e $tp.sed) then
-   echo "Cannot access $tp.sed"
+    set fout = $arg[3]
 endif
 
 set tmp = $$
+if (! -e $tp.sed) then
+    echo "Cannot access $tp.sed"
+    exit 1
+endif
+
 sed -f $tp.sed $fin >! $tmp.tmp
 
 mv -f $tmp.tmp $fout
+
+unset tmp
 
 exit 0
 
