Forgot to save the file before I checked it ie earlier today, oops. Lucky I noticed.

diff --git a/code/install/assay b/code/install/assay
--- a/code/install/assay
+++ b/code/install/assay
@@ -170,8 +170,13 @@
         exit
      fi
   else
-     echo "FAIL (execution failure): $*"
-     STATUS=1
+     STATUS=$?
+     if [ $STATUS = 3 ]
+     then
+        echo "UNTESTED: $*"
+     else
+        echo "FAIL (execution failure): $*"
+     fi
      exit
   fi
 
